# This workflow outlines tasks that are ran when a pull request that modifies source code is made, such as building a preview

name: "PR: Code Changes"

on:
  pull_request:
    branches: [main]
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".goreleaser.yml"

jobs:
  # Check to see if an invalid file has been modified, if it has then fail.
  No-Invalid-Edits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Edited Files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: "json"
          filters: |
            src:
              - 'proto.rb'

      - name: Post Comment on Invalid Changes
        if: steps.changes.outputs.src == 'true'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "A preview-build was not generated as a security measure as invalid files have been modified, please refer to the contributing guide for information."
          comment_includes: "preview-build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail CI on Invalid Edit
        if: steps.changes.outputs.src == 'true'
        run: |
          echo "::error::Contains invalid file edits"
          exit 1

  # Check to see if any new dependency in this pull request is vulnerable.
  Dependency-Review:
    runs-on: ubuntu-latest
    needs: ["No-Invalid-Edits"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v1

      - name: Post Comment on Insecure Changes
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "A preview-build was not generated as a security measure due to this pull request containing insecure dependencies."
          comment_includes: "preview-build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # If all is good, create a preview build for the pull request if needed.
  Preview:
    runs-on: ubuntu-latest
    needs: ["Dependency-Review", "No-Invalid-Edits"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Post/Edit Initial Build Comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### Building ${{ github.repository}} <span aria-hidden="true">🚧</span>
            Please wait, this could take several minutes to complete. This comment will be edited when finished.

            |  Name | Detail |
            |---------------------------------|-------------------------------------------------------------------------------------|
            | **Commit** 						          | ${{ github.sha }}                                                                   |
            | **Logs** 							          | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | **Build Environment** 			    | ${{ runner.os }}/${{ runner.arch }}                                                 |
            | **Triggered By**							  | [${{ github.actor }}](https://github.com/${{ github.actor }})                       |

            identifier: preview-build
          comment_includes: "preview-build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

     - id: go-cache-paths
       run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist/proto*_*/*
            checksums.txt

      - name: Post/Edit Build Comment (Success)
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### Build Complete for ${{ github.repository }} <span aria-hidden="true">⚡</span>
            All builds finished without issues and any artifact(s) have been uploaded.

            |  Name | Detail |
            |---------------------------------|-------------------------------------------------------------------------------------|
            | **Commit** 						          | ${{ github.sha }}                                                                   |
            | **Logs** 							          | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | **Build Environment** 			    | ${{ runner.os }}/${{ runner.arch }}                                                 |
            | **Triggered By**							  | [${{ github.actor }}](https://github.com/${{ github.actor }})                       |

            *Please review the code before downloading any artifacts for security reasons.* 

            identifier: preview-build
          comment_includes: "preview-build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post/Edit Build Comment (Failure)
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### Build Failed for ${{ github.repository }} <span aria-hidden="true">⚠️</span>
            Something went wrong when running a build, please view the logs for more information about this.

            |  Name | Detail |
            |---------------------------------|-------------------------------------------------------------------------------------|
            | **Commit** 						          | ${{ github.sha }}                                                                   |
            | **Logs** 							          | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | **Build Environment** 			    | ${{ runner.os }}/${{ runner.arch }}                                                 |
            | **Triggered By**							  | [${{ github.actor }}](https://github.com/${{ github.actor }})                       |

            identifier: preview-build
          comment_includes: "preview-build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
